apiVersion: v1
kind: ConfigMap
metadata:
  name: ilb-gateway
data:  
  nginx.conf: |
    user  root;
    worker_processes  1;
    daemon off;

    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;


    events {
        worker_connections  1024;
    }

    http {
        server_names_hash_bucket_size 128;
        server_names_hash_max_size 4096;
        limit_req_zone $binary_remote_addr zone=flood:50m rate=90r/s;
        limit_conn_zone $binary_remote_addr zone=addr:50m;

        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';

        access_log  /var/log/nginx/access.log  main;

        sendfile        on;
        #tcp_nopush     on;

        keepalive_timeout  65;

        #gzip  on;

        # Expose NGINX status endpoint
        server {
          listen 1010;
          server_name health;
          location / {
            stub_status on;
            access_log off;
          }
        }

        # temporary endpoints for testing purposes
        server {
          listen 8888;
          access_log /var/log/nginx/hello-app_access.log;
          server_name localbalancer-hello-app.production.travelaudience.cloud;
          location / {
            proxy_pass http://hello-app:8888;
          }
        }
        server {
          listen 8888;
          access_log /var/log/nginx/hello-app2_access.log;
          server_name localbalancer-hello-app2.production.travelaudience.cloud;
          location / {
            add_header Content-Type text/plain;
            return 200 'ok';
          }
        }

        # k8s services forwarding while VPC peering/ILBs are not fixed
        server {
          listen 8080 http2;
          charset utf-8;
          access_log /var/log/nginx/campaignenrichserv_access.log;

          server_name campaignenrichserv.production.travelaudience.cloud;
          location / {
            grpc_pass grpc://campaignenrichservd:8080;
          }
        }

        server {
          listen 8080 http2;
          charset utf-8;
          access_log /var/log/nginx/offerbiddingserv_access.log;

          server_name offerbiddingserv.production.travelaudience.cloud;
          location / {
            grpc_pass grpc://offerbiddingservd:8080;
          }
        }

        server {
          listen 8080 http2;
          charset utf-8;
          access_log /var/log/nginx/advertiserserv_access.log;

          server_name advertiserserv.production.travelaudience.cloud;
          location / {
            grpc_pass grpc://advertiserservd:8080;
          }
        }

        server {
          listen 9000 http2;
          charset utf-8;
          access_log /var/log/nginx/budgetserv_access.log;

          server_name budgetserv.production.travelaudience.cloud;
          location / {
            grpc_pass grpc://budgetserv:9000;
          }
        }

        server {
          listen 8080 http2;
          charset utf-8;
          access_log /var/log/nginx/charon_access.log;

          server_name charon.production.travelaudience.cloud;
          location / {
            grpc_pass grpc://charond:8080;
          }
        }

        server {
          listen 8080 http2;
          charset utf-8;
          access_log /var/log/nginx/creativeserv_access.log;

          server_name creativeserv.production.travelaudience.cloud;
          location / {
            grpc_pass grpc://creativeservd:8080;
          }
        }

        server {
          listen 8080 http2;
          charset utf-8;
          access_log /var/log/nginx/offerdeliveryserv_access.log;

          server_name offerdeliveryserv.production.travelaudience.cloud;
          location / {
            grpc_pass grpc://offerdeliveryservd:8080;
          }
        }

        server {
          listen 8080 http2;
          charset utf-8;
          access_log /var/log/nginx/publisherserv_access.log;

          server_name publisherserv.production.travelaudience.cloud;
          location / {
            grpc_pass grpc://publisherservd:8080;
          }
        }

        include /etc/nginx/conf.d/*.conf;
    }
